server:
  port: 8090

spring:
#  config:
#    import: "classpath:config.properties"
  mail:
    username: pratiksambhe.eidiko@gmail.com
    password: qtfaqqivvkvkffjt
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: AUg5_SpringProject
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  oracle:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: Eidiko3
      password: sarasu10
      driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true