server:
  port: 8096

spring:
  application:
    name: SecurityDemo2

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: Eidiko3
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
